services:
  apache:
    image: "recruitment-apache"
    ports:
      - "82:8082"
    links:
      - "tomcat-gui:tomcat-gui"

  tomcat-api:
    image: "recruitment-tomcat-api"
    ports:      
      - "81:8081"

  tomcat-gui:
    image: "recruitment-tomcat-gui"
    ports:
      - "8080:8080"  # Zmieniono port na 8080, aby uniknąć konfliktu z apache
    links:
      - "tomcat-api:tomcat-api"